### ISSUE TITLE
Homework Tasks

### ISSUE THREAD

**Issue by tombissaillon** [tombissaillon/Homework#1]
### Description
This issue is intended to keep track of homework tasks that need to be completed

### Tasks

- [x] Task 1: Set up Overleaf and LaTex
- [x] Task 2: Complete git branching training
- [x] Task 3: Create Github issue and task tracker

### Progress
- Total tasks: 3
- Completed tasks: 3
